baseURL = "/"
languageCode = "en-us"
title = "Totem Software"
themesDir = "themes"
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.homepage_meta_tags]
    meta_description = "Totem Software company website"
    meta_og_title = "Totem Software"
    meta_og_type = "website"
    meta_og_url = "https://www.totemsoft.com.au"
    meta_og_image = "https://www.mywebsite.com/images/tn.png"
    meta_og_description = "Totem Software company website"
    meta_twitter_card = "summary"
    meta_twitter_site = "@bezdomniy"
    meta_twitter_creator = "@bezdomniy"

  [params.logo]
    mobile = "images/logo.png"
    mobile_height = "36px"
    desktop = "images/logo.png"
    desktop_height = "36px"
    alt = "Totem Software"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#f24088"
    secondary = "#f88379"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    steel = "#5C5A5A"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"
    meta_og_image = "https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = ''

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
# order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "totemsoft-deployment"
# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://totemsoftware.com.au?region=ap-southest-2"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
#cloudFrontDistributionID = <ID>

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "must-revalidate, no-cache, max-age=0, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
