#baseURL = "http://example.org/"
baseURL = "/"
languageCode = "en-us"
title = "Totem Software"
themesDir = "themes"
theme = "hugo-serif-theme"

[module]
  [[module.imports]]
    path = "github.com/zerostaticthemes/hugo-serif-theme"

[params]
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage_meta_tags]
    meta_description = "Totem Software company website"
    meta_og_title = "Totem Software"
    meta_og_type = "website"
    meta_og_url = "https://www.totemsoft.com.au"
    meta_og_image = "https://www.mywebsite.com/images/tn.png"
    meta_og_description = "Totem Software company website"
    meta_twitter_card = "summary"
    meta_twitter_site = "@bezdomniy"
    meta_twitter_creator = "@bezdomniy"

    [params.logo]
      mobile = "images/logo.png"
      mobile_height = "36px"
      desktop = "images/logo.png"
      desktop_height = "36px"
      alt = "Totem Software"
    [params.footer]
      copyright_text = ''

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
# order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "totemsoft-deployment"
# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://totemsoftware.com.au?region=ap-southest-2"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
#cloudFrontDistributionID = <ID>

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
